### ISSUE TITLE
Two more things to take care of

### ISSUE THREAD

**Issue by dpa1983** [NuGrid/mesa_h5#1]
My test of mesa_h5 with MESA revision r9331 has run successfully after the following two changes:

First, the new mesa_h5 uses the names of the files it outputs to the directory HDF5 that end with ".h5", while the NuGrid MPPNP code reads in files with names ending with ".se.h5". I had to change the endings from ".se.h5" to ".h5" in two places in my local copy of mppnp. 

Second, the history_columns.list file provided by JC, that I used, doesn't activate the parameter "time_step" which becomes "delta' in mppnp. I had to un-comment "time_step" in JC's history_columns.list file.

I have compared CNO abundance profiles in a 15 Msun model star at the end of its MS evolution post-processed with mppnp using se files prepared by old se with MESA r7624 and new mesa_h5 with MESA r9331. They are identical.

I have noticed that MESA r9331 works slower than r7624, but I think this is a mesa issue, because I recall a discussion of this problem on mesa forum.

**Comment by jcpassy** [comment]
Glad to hear that the HDF5 framework is working. Pavel, about your comments:

1) As far as I remember, Falk and I decided to drop the ".se.h5" extension name and replace it with simply ".h5". This is because the HDF5 framework is technically independent from mppnp. Since we want to make it part of MESA, it does not make sense to name it after SE. So I think mppnp should actually be modified to take .h5 files as an input, not the other way around.

2) That is fine. Similarly, you should decide whether you want to keep the variable names currently in mppnp (such as _deltat_) or modify some of them to use the MESA ones (_deltat_ -> _time_step_).

**Comment by fherwig** [comment]
@swjones - could you comment on @jcpassy suggestions? `se.h5` vs `h5` and changing `deltat` to `time_step`

**Comment by jcpassy** [comment]
And also about the (A,Z) structure and the problem that might occur if the network is dynamically changing (see README for details).
Let's try to finish this asap, it has been hanging for too long!

**Comment by fherwig** [comment]
I am just now trying to do a test on this myself. I am trying to compile 9331 without MESA SDK because I do not want to install X11 (I try to do it in a docker). But kap throws an error. So I may try it with MESA SDK.

**Comment by fherwig** [comment]
Here is the verdict: 

1. on the issue _".se.h5" vs ".h5" - we will call the files ".se.h5" when they are written with mesa_h5. It makes it clear that this is the se way of writing h5 files. se is an additional set of conditions on top of h5. I will change that in `mesa_hdf5_routines.inc`. 
2. I have updated the history/profiles_inlist files.

**Comment by fherwig** [comment]
This is done
